name: Daily Trading Analysis

on:
  schedule:
    # Run every weekday at 4:30 PM EST (21:30 UTC) - after market close
    - cron: '30 21 * * 1-5'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      ticker:
        description: 'Stock ticker to analyze'
        required: false
        default: 'GLD'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Run analysis
      env:
        EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TICKER: ${{ github.event.inputs.ticker || 'GLD' }}
      run: |
        python main_analysis.py
    
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update analysis results - $(date +'%Y-%m-%d %H:%M')" && git push)
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: |
          data/signals.csv
          data/signals_latest.json
          data/backtest_results.json
          data/analysis_summary.json
        retention-days: 30
    
    - name: Deploy to Streamlit Cloud
      if: success()
      run: |
        echo "Dashboard will auto-update on Streamlit Cloud"
        echo "Visit: https://kriterion-quant.streamlit.app"
